Compatibility bfw v3.0.0-rc11

diff --git a/test/run/installer_procedural b/test/run/installer_procedural
--- a/test/run/installer_procedural
+++ b/test/run/installer_procedural
@@ -15,7 +15,7 @@ php composer.phar install
 
 echo '\033[0;33mBFW Install and module\033[0m'
 ./vendor/bin/bfwInstall
-./vendor/bin/bfwInstallModules
+./vendor/bin/bfwAddMod -a
 
 echo '\033[0;33mCopy module test skeleton files\033[0m'
 cd ../
@@ -23,9 +23,46 @@ mv install_procedural/app/config/bfw/modules.php install_procedural/app/config/b
 cp -R skeleton_common/app/* install_procedural/app/
 cp -R skeleton_procedural/app/* install_procedural/app/
 cp -R skeleton_procedural/src/* install_procedural/src/
+cd install_procedural
+
+echo '\033[0;33mEnable all modules\033[0m'
+./vendor/bin/bfwEnMod -a
+
+DIRECTORY=`pwd`
+
+echo -n '\033[0;33mCheck module installed script has been executed ... \033[0m'
+if [ -d "$DIRECTORY/src/controllers" ]; then
+    echo '\033[1;32mOK\033[0m'
+else
+    echo '\033[1;31mFail\033[0m'
+    exit 1
+fi
+
+echo -n '\033[0;33mCheck module bfw-controller is available ... \033[0m'
+if [ -d "$DIRECTORY/app/modules/available/bfw-controller" ]; then
+    echo '\033[1;32mOK\033[0m'
+else
+    echo '\033[1;31mFail\033[0m'
+    exit 1
+fi
+
+echo -n '\033[0;33mCheck module bfw-controller is enabled ... \033[0m'
+if [ -d "$DIRECTORY/app/modules/enabled/bfw-controller" ]; then
+    echo '\033[1;32mOK\033[0m'
+else
+    echo '\033[1;31mFail\033[0m'
+    exit 1
+fi
+
+echo -n '\033[0;33mCheck module forceRoute is enabled ... \033[0m'
+if [ -d "$DIRECTORY/app/modules/enabled/forceRoute" ]; then
+    echo '\033[1;32mOK\033[0m'
+else
+    echo '\033[1;31mFail\033[0m'
+    exit 1
+fi
 
 echo '\033[0;33mRun php integrated web server\033[0m'
-cd install_procedural
 php -S localhost:8001 -t web web/index.php &
 
 echo '\033[0;33mWait 5s web server is running\033[0m'
